---
title: "01NAEX - Home project 01 - Dot in circle problem"
author: "Jiri Franc and his friends"
date: "2021/10/12"
output:
  html_document:
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# get requirements for this exercise
list_of_packages <- c("tidyverse", "car", "lattice", "pwr", "MASS","GGally")
missing_packages <- list_of_packages[!(list_of_packages %in% installed.packages()[,"Package"])]
if(length(missing_packages)) install.packages(missing_packages)
lapply(list_of_packages, library, character.only = TRUE)

######################
# check our settings
#getwd()
#print(.libPaths())
#print(sessionInfo())
#print(version)
```


## Home exercise:

V tomto úkolu zjistěte, jaký má vliv velikost kruhu a použití ruky, kterou experiment provádíme (levá, pravá, obě) na počet teček uvnitř kruhu. 

# Provedení: 

Využijte šablonu a po dobu 10 sekund se snažte udělat na střídačku  do obou kruhů co nejvíce teček.
            Dělejte tečky, né čáry přes půlku kruhu a penalizujte se za tečky mimo.

# Odevzdání: 

Vypracované řešení úkolu odevzdejte do 29. 10. 2021 ve formátu pdf + Rmd/jpnb.


# Otázky: 


 1. namerte data: experiment nastavte tak, a byl znahodneny !!!!!
                  poradi mereni si poznamenejte pro dalsi kontrolu pripadne zavislosti na poradi mereni
                  Jednotlive lidi ve skupine berte jako ruzne operatory experimentu (blokujte)
                  Pocet replikaci u jednoho cloveka a jednoho casu vemte 1

  2.  Spoctete zakladni statistiky (mean, median a sd pro jednotlive faktory - velikost, ruka, operator)
      Zobrazte namerena data (box plot, interaction plot, effects plot, ...) a okomentujte je
      co z danych obrazku muzeme pred samotnou analyzou rici o vysledku?
  
   3. Zamerte se zvlaste na faktory ruka a velikost kola. Otestujte hypotezu o schodnosti rozptylu pro jednotlive urovne  a vhodnym testem overte stejnost strednich hodnot. 
      Provedte Tukey HSD a Fisher LSD test pro parove porovnani stednich hodnot jednotlivych skupin s vybranou korekci phodnoty.

   4. Analyzute data pomoci ANOVA (vsechny promenne berte jako faktor)
      * s predpokladem, ze kazdy z ucastniku experimentu tvori jeden blok.
      * diskutujte vysledky, overte predpoklady, vykreslete QQ-plot, residua x fitted values, residua x cas.
      * diskutujte vliv znahodneni experimentu a vyvoj rezidui v case (cislo mereni)

   5. Porovnejte a diskutujte vysledky z bodu 3 a 4.

   6. Pokud data nesplnuji predpoklady pro pouziti ANOVA, diskutujte mozne transformace (logaritmicka, Box-Cox, ...)
      a duvod proc data predpoklady nesplnuji? Vyskyt outlieru, zpusob mereni, divny operator, ...

   7. Vyberte nejvhodnejsi model a i kdyby nesplnoval predpoklady pro pouziti ANOVA reste nasledujici: 
      * Spoctete silu testu v ANOVA (pro max. dvoufaktorovou analyzu - jeden z faktoru zanedbejte, nebo vezmete mereni pro jednu jeho konkretni uroven)
      * Predpokladejme, ze standartni odchylka disturbanci bude pro provadeny experiment 4 a maximalni (pro nas signifikantni) rozdil, ktery chceme detekovat je 5 bodu v kruhu. Spoctete pocet potrebnych replikaci, aby sila vysledneho testu byla vetsi nez 0.9
 
   8. Vytvorte regresni model, kde nebudete uvazovat bloky a velikost kruhu bude kvantitativni promenna.
      * zkuste pridat do modelu i druhou mocninu a porovnejte dva regresni modely mezi s sebou a vyberte vhodnejsi
      * overte predpoklady pro pouziti vybraneho modelu a vykreslete QQ-plot, residua x fitted values, residua x prumer.


   Pozn: V připadě, že bloky jsou velmi dominantní a žádná z dalších proměnných se nejeví významná,
      použijte pro výslednou analýzu jen "operátora s daty nejlepšími pro akademicke účely".

